program DASHA;

uses
  Forms,
  SIGMA00 in 'Units\SIGMA00.pas' {frmMain},
  SIGMA01 in 'Units\SIGMA01.pas' {DM: TDataModule},
  PVENTA02 in 'PVenta\Units\PVENTA02.pas' {frmAcceso},
  PVENTA03 in 'PVenta\Units\PVENTA03.pas' {frmEmpresas},
  PVENTA04 in 'PVenta\Units\PVENTA04.pas' {frmTipoClientes},
  PVENTA05 in 'PVenta\Units\PVENTA05.pas' {frmCajeros},
  PVENTA06 in 'PVenta\Units\PVENTA06.pas' {frmAlmacenes},
  PVENTA07 in 'PVenta\Units\PVENTA07.pas' {frmCondiciones},
  PVENTA08 in 'PVenta\Units\PVENTA08.pas' {frmFormasPago},
  PVENTA09 in 'PVenta\Units\PVENTA09.pas' {frmTipoFacturas},
  PVENTA10 in 'PVenta\Units\PVENTA10.pas' {frmDeptos},
  PVENTA11 in 'PVenta\Units\PVENTA11.pas' {frmFamilias},
  PVENTA12 in 'PVenta\Units\PVENTA12.pas' {frmUsuarios},
  PVENTA13 in 'PVenta\Units\PVENTA13.pas' {frmProveedores},
  PVENTA14 in 'PVenta\Units\PVENTA14.pas' {frmClientes},
  PVENTA15 in 'PVenta\Units\PVENTA15.pas' {frmProductos},
  PVENTA16 in 'PVenta\Units\PVENTA16.pas' {frmColores},
  PVENTA17 in 'PVenta\Units\PVENTA17.pas' {frmOfertas},
  PVENTA232 in 'PVenta\Units\PVENTA232.pas' {frmFacturaRenta},
  PVENTA19 in 'PVenta\Units\PVENTA19.pas' {frmPedidosCli},
  PVENTA20 in 'PVenta\Units\PVENTA20.pas' {frmPedidosProv},
  PVENTA21 in 'PVenta\Units\PVENTA21.pas' {frmNotasCR},
  PVENTA22 in 'PVenta\Units\PVENTA22.pas' {frmNotasDB},
  PVENTA23 in 'PVenta\Units\PVENTA23.pas' {frmDevolucion},
  PVENTA24 in 'PVenta\Units\PVENTA24.pas' {frmRecibos},
  PVENTA25 in 'PVenta\Units\PVENTA25.pas' {frmDesembolsos},
  PRENTA02 in 'PVenta\Units\PRENTA02.pas' {frmAlquiler},
  PVENTA27 in 'PVenta\Units\PVENTA27.pas' {frmEntradas},
  PVENTA28 in 'PVenta\Units\PVENTA28.pas' {frmConduce},
  PVENTA29 in 'PVenta\Units\PVENTA29.pas' {frmInvFisico},
  PVENTA30 in 'PVenta\Units\PVENTA30.pas' {frmTransferencia},
  PVENTA31 in 'PVenta\Units\PVENTA31.pas' {frmAcerca},
  PVENTA32 in 'PVenta\Units\PVENTA32.pas' {frmVendedor},
  PVENTA33 in 'PVenta\Units\PVENTA33.pas' {frmBuscaProducto},
  PVENTA34 in 'PVenta\Units\PVENTA34.pas' {frmPrecios},
  PVENTA35 in 'PVenta\Units\PVENTA35.pas' {frmCargos},
  PVENTA36 in 'PVenta\Units\PVENTA36.pas' {frmNota},
  PVENTA239 in 'PVenta\Units\PVENTA239.pas' {frmPideAutorizacion},
  PVENTA38 in 'PVenta\Units\PVENTA38.pas' {frmPVenta},
  PVENTA39 in 'PVenta\Units\PVENTA39.pas' {frmModificaPrecio},
  PVENTA40 in 'PVenta\Units\PVENTA40.pas' {frmOtrosFac},
  PVENTA41 in 'PVenta\Units\PVENTA41.pas' {frmSerieFactura},
  PVENTA42 in 'PVenta\Units\PVENTA42.pas' {frmBuscaFactura},
  PVENTA43 in 'PVenta\Units\PVENTA43.pas' {frmFormaPagoFac},
  PVENTA230 in 'PVenta\Units\PVENTA230.pas' {frmConsFTEnvios},
  PVENTA45 in 'PVenta\Units\PVENTA45.pas' {frmFacProvee},
  PVENTA46 in 'PVenta\Units\PVENTA46.pas' {frmConsSerie},
  PVENTA47 in 'PVenta\Units\PVENTA47.pas' {frmCuadre},
  PVENTA48 in 'PVenta\Units\PVENTA48.pas' {frmConsRecibos},
  PVENTA49 in 'PVenta\Units\PVENTA49.pas' {frmConsDesem},
  PVENTA50 in 'PVenta\Units\PVENTA50.pas' {frmConsDev},
  PVENTA51 in 'PVenta\Units\PVENTA51.pas' {frmConsNC},
  PVENTA52 in 'PVenta\Units\PVENTA52.pas' {frmConsDB},
  PVENTA53 in 'PVenta\Units\PVENTA53.pas' {frmConsEntrada},
  PVENTA54 in 'PVenta\Units\PVENTA54.pas' {frmConsConduce},
  PVENTA55 in 'PVenta\Units\PVENTA55.pas' {frmConsBeneficio},
  PVENTA56 in 'PVenta\Units\PVENTA56.pas' {frmConsProdCliente},
  PVENTA57 in 'PVenta\Units\PVENTA57.pas' {frmConsFacturasProd},
  PVENTA58 in 'PVenta\Units\PVENTA58.pas' {frmConsCxP},
  PVENTA59 in 'PVenta\Units\PVENTA59.pas' {frmTipoMov},
  PVENTA60 in 'PVenta\Units\PVENTA60.pas' {frmConsCxC},
  PVENTA62 in 'PVenta\Units\PVENTA62.pas' {frmConsFacProvee},
  PVENTA63 in 'PVenta\Units\PVENTA63.pas' {frmConsPedidosCli},
  PVENTA64 in 'PVenta\Units\PVENTA64.pas' {frmConsPedidosProv},
  PVENTA65 in 'PVenta\Units\PVENTA65.pas' {frmRepClientes},
  PVENTA66 in 'PVenta\Units\PVENTA66.pas' {frmRepProveedores},
  PVENTA67 in 'PVenta\Units\PVENTA67.pas' {frmRepMovDia},
  PVENTA68 in 'PVenta\Units\PVENTA68.pas' {frmRepPrecios},
  PVENTA69 in 'PVenta\Units\PVENTA69.pas' {frmReimpresion},
  PVENTA70 in 'PVenta\Units\PVENTA70.pas' {frmAnulaFac},
  PVENTA71 in 'PVenta\Units\PVENTA71.pas' {frmAnulaNC},
  PVENTA72 in 'PVenta\Units\PVENTA72.pas' {frmGeneraRec},
  PVENTA73 in 'PVenta\Units\PVENTA73.pas' {frmEstadoCtaCli},
  PVENTA74 in 'PVenta\Units\PVENTA74.pas' {RAntigSaldo: TQuickRep},
  PVENTA77 in 'PVenta\Units\PVENTA77.pas' {frmExistProducto},
  PVENTA78 in 'PVenta\Units\PVENTA78.pas' {frmLimite},
  PVENTA79 in 'PVenta\Units\PVENTA79.pas' {frmRepFPago},
  PVENTA99 in 'PVenta\Units\PVENTA99.pas' {frmAnulaCond},
  PVENTA81 in 'PVenta\Units\PVENTA81.pas' {frmMontoFPago},
  PVENTA82 in 'PVenta\Units\PVENTA82.pas' {frmConsBalance},
  PVENTA83 in 'PVenta\Units\PVENTA83.pas' {frmImpPantalla},
  PVENTA84 in 'PVenta\Units\PVENTA84.pas' {frmEstadoCtaProv},
  PVENTA85 in 'PVenta\Units\PVENTA85.pas' {frmRepProdVendidos},
  PVENTA86 in 'PVenta\Units\PVENTA86.pas' {frmRepVentaCliente},
  PVENTA87 in 'PVenta\Units\PVENTA87.pas' {frmConsComision},
  PVENTA88 in 'PVenta\Units\PVENTA88.pas' {frmConsTransferencia},
  PVENTA89 in 'PVenta\Units\PVENTA89.pas' {frmAsignaCliente},
  PVENTA90 in 'PVenta\Units\PVENTA90.pas' {frmCierreDia},
  PVENTA91 in 'PVenta\Units\PVENTA91.pas' {frmActBalance},
  PVENTA92 in 'PVenta\Units\PVENTA92.pas' {frmAnulaND},
  PVENTA93 in 'PVenta\Units\PVENTA93.pas' {frmAnulaDev},
  PVENTA94 in 'PVenta\Units\PVENTA94.pas' {frmRepVentaTipoFac},
  PVENTA95 in 'PVenta\Units\PVENTA95.pas' {frmAnulaREC},
  PVENTA96 in 'PVenta\Units\PVENTA96.pas' {frmAnulaDesem},
  PVENTA97 in 'PVenta\Units\PVENTA97.pas' {frmDevDinero},
  PVENTA98 in 'PVenta\Units\PVENTA98.pas' {frmAnulaEnt},
  PVENTA80 in 'PVenta\Units\PVENTA80.pas' {frmParametros},
  PVENTA100 in 'PVenta\Units\PVENTA100.pas' {frmAnulaProvFact},
  PVENTA110 in 'PVenta\Units\PVENTA110.pas' {frmCambiaStatus},
  PVENTA101 in 'PVenta\Units\PVENTA101.pas' {frmDevSinFactura},
  PVENTA102 in 'PVenta\Units\PVENTA102.pas' {frmMarcas},
  PVENTA103 in 'PVenta\Units\PVENTA103.pas' {RRepServicios: TQuickRep},
  PVENTA104 in 'PVenta\Units\PVENTA104.pas' {frmRepVentaFamilia},
  PVENTA105 in 'PVenta\Units\PVENTA105.pas' {frmRepVentaDepto},
  PVENTA106 in 'PVenta\Units\PVENTA106.pas' {frmRepVentaMarca},
  PVENTA107 in 'PVenta\Units\PVENTA107.pas' {frmAnulaPago},
  PVENTA109 in 'PVenta\Units\PVENTA109.pas' {frmRepProdVencidos},
  PVENTA114 in 'PVenta\Units\PVENTA114.pas' {frmGeneraCuotas},
  PVENTA113 in 'PVenta\Units\PVENTA113.pas' {frmConsOperaciones},
  PVENTA111 in 'PVenta\Units\PVENTA111.pas' {frmRepCodigoBarra},
  PVENTA112 in 'PVenta\Units\PVENTA112.pas' {frmVencimiento},
  PVENTA115 in 'PVenta\Units\PVENTA115.pas' {frmRepFisico},
  PVENTA116 in 'PVenta\Units\PVENTA116.pas' {frmEscala},
  PVENTA117 in 'PVenta\Units\PVENTA117.pas' {frmSelEscala},
  PVENTA118 in 'PVenta\Units\PVENTA118.pas' {frmAccesoEmp},
  PVENTA119 in 'PVenta\Units\PVENTA119.pas' {frmSeleccionEmp},
  PVENTA120 in 'PVenta\Units\PVENTA120.pas' {frmEstadisticas},
  PVENTA121 in 'PVenta\Units\PVENTA121.pas' {frmConsCombo},
  PVENTA122 in 'PVenta\Units\PVENTA122.pas' {frmDevolucionCompra},
  PVENTA123 in 'PVenta\Units\PVENTA123.pas' {frmChequeDevol},
  PVENTA124 in 'PVenta\Units\PVENTA124.pas' {frmCentroCosto},
  PVENTA125 in 'PVenta\Units\PVENTA125.pas' {frmDevueltaEfectivo},
  PVENTA126 in 'PVenta\Units\PVENTA126.pas' {frmCantidadCombo},
  PVENTA127 in 'PVenta\Units\PVENTA127.pas' {frmConsDevCompra},
  PVENTA128 in 'PVenta\Units\PVENTA128.pas' {frmMovProductoFactura},
  PVENTA129 in 'PVenta\Units\PVENTA129.pas' {frmConsEquivalencias},
  PVENTA130 in 'PVenta\Units\PVENTA130.pas' {frmCotMultiple},
  PVENTA131 in 'PVenta\Units\PVENTA131.pas' {frmRepValorInventario},
  PVENTA132 in 'PVenta\Units\PVENTA132.pas' {frmActividadCaja},
  PVENTA133 in 'PVenta\Units\PVENTA133.pas' {frmMoneda},
  PVENTA134 in 'PVenta\Units\PVENTA134.pas' {frmDescuentoGeneral},
  PVENTA135 in 'PVenta\Units\PVENTA135.pas' {frmConsCentroCosto},
  PVENTA136 in 'PVenta\Units\PVENTA136.pas' {frmLiquidacion},
  PVENTA137 in 'PVenta\Units\PVENTA137.pas' {frmSucursales},
  PVENTA138 in 'PVenta\Units\PVENTA138.pas' {frmAjusteInventario},
  PVENTA139 in 'PVenta\Units\PVENTA139.pas' {frmRepSolicitados},
  PVENTA140 in 'PVenta\Units\PVENTA140.pas' {frmOrdenPedido},
  PVENTA141 in 'PVenta\Units\PVENTA141.pas' {frmImprimeBarraCompra},
  PVENTA142 in 'PVenta\Units\PVENTA142.pas' {frmDevolucionCxpProductos},
  PVENTA143 in 'PVenta\Units\PVENTA143.pas' {frmRecetaOptica},
  PVENTA144 in 'PVenta\Units\PVENTA144.pas' {frmNotaCreditoCompra},
  PVENTA146 in 'PVenta\Units\PVENTA146.pas' {frmClientesClub},
  PVENTA147 in 'PVenta\Units\PVENTA147.pas' {frmBono},
  PVENTA148 in 'PVenta\Units\PVENTA148.pas' {frmConsBonos},
  PVENTA149 in 'PVenta\Units\PVENTA149.pas' {frmProvincias},
  PVENTA150 in 'PVenta\Units\PVENTA150.pas' {frmMesas},
  PVENTA151 in 'PVenta\Units\PVENTA151.pas' {frmConsTicket},
  PVENTA152 in 'PVenta\Units\PVENTA152.pas' {frmConsVentaProvincia},
  PVENTA153 in 'PVenta\Units\PVENTA153.pas' {frmRepConciliacion},
  PVENTA154 in 'PVenta\Units\PVENTA154.pas' {frmProcesoColector},
  PVENTA157 in 'PVenta\Units\PVENTA157.pas' {frmClaveSupervisor},
  PVENTA158 in 'PVenta\Units\PVENTA158.pas' {frmSupervisoresCaja},
  PVENTA159 in 'PVenta\Units\PVENTA159.pas' {frmConsNCProveedores},
  PVENTA155 in 'PVenta\Units\PVENTA155.pas' {frmRepHistorialCliente},
  PVENTA156 in 'PVenta\Units\PVENTA156.pas' {frmRepHistorialSuplidor},
  PVENTA162 in 'PVenta\Units\PVENTA162.pas' {frmDigitacionAbierta},
  PVENTA164 in 'PVenta\Units\PVENTA164.pas' {frmRepVentaTipoCliente},
  PVENTA165 in 'PVenta\Units\PVENTA165.pas' {frmRepCumpleanos},
  PVENTA166 in 'PVenta\Units\PVENTA166.pas' {frmConsVentasMarca},
  PVENTA167 in 'PVenta\Units\PVENTA167.pas' {frmRepProdRotacion},
  PVENTA168 in 'PVenta\Units\PVENTA168.pas' {frmReprentabilidad},
  PVENTA169 in 'PVenta\Units\PVENTA169.pas' {frmGastosAduanales},
  PVENTA170 in 'PVenta\Units\PVENTA170.pas' {frmCuadreDesgloce},
  PVENTA171 in 'PVenta\Units\PVENTA171.pas' {frmRepOfertasOtorgadas},
  PVENTA172 in 'PVenta\Units\PVENTA172.pas' {frmEliminarProducto},
  PVENTA173 in 'PVenta\Units\PVENTA173.pas' {frmAnulaDevCompra},
  PVENTA174 in 'PVenta\Units\PVENTA174.pas' {frmAnulaNCCompra},
  PVENTA175 in 'PVenta\Units\PVENTA175.pas' {frmPronosticoCobro},
  PVENTA176 in 'PVenta\Units\PVENTA176.pas' {frmOperaciones},
  PVENTA177 in 'PVenta\Units\PVENTA177.pas' {frmPreventas},
  PVENTA178 in 'PVenta\Units\PVENTA178.pas' {frmProductosDespachados},
  PVENTA179 in 'PVenta\Units\PVENTA179.pas' {frmCourriers},
  PVENTA180 in 'PVenta\Units\PVENTA180.pas' {frmAnulaOrden},
  PVENTA181 in 'PVenta\Units\PVENTA181.pas' {frmConsCotizaciones},
  PVENTA182 in 'PVenta\Units\PVENTA182.pas' {frmCajasIP},
  PVENTA183 in 'PVenta\Units\PVENTA183.pas' {frmCuadreCajasIP},
  RVENTA92 in 'PVenta\Reports\RVENTA92.pas' {RExistProdGeneral: TQuickRep},
  PVENTA184 in 'PVenta\Units\PVENTA184.pas' {frmConsResumenEjecutivo},
  PVENTA185 in 'PVenta\Units\PVENTA185.pas' {frmBuscaRNC},
  PVENTA186 in 'PVenta\Units\PVENTA186.pas' {frmConsProdClienteFac},
  PVENTA187 in 'PVenta\Units\PVENTA187.pas' {frnAmalisisCompraVenta},
  PVENTA188 in 'PVenta\Units\PVENTA188.pas' {frmMotivoDevolucion},
  PVENTA189 in 'PVenta\Units\PVENTA189.pas' {frmAnalisisCompra_Venta},
  PVENTA190 in 'PVenta\Units\PVENTA190.pas' {frmConsLiquidaciones},
  PVENTA191 in 'PVenta\Units\PVENTA191.pas' {frmRepInvFamilia},
  PVENTA192 in 'PVenta\Units\PVENTA192.pas' {frmRepInvFamiliaDepto},
  PVENTA193 in 'PVenta\Units\PVENTA193.pas' {frmRepVentaFamiliaDepto},
  PVENTA194 in 'PVenta\Units\PVENTA194.pas' {frmRepCxCVendedorProvincia},
  PVENTA195 in 'PVenta\Units\PVENTA195.pas' {frmAnulaLiq},
  PVENTA196 in 'PVenta\Units\PVENTA196.pas' {frmMargenBruto},
  PVENTA197 in 'PVenta\Units\PVENTA197.pas' {frmGerentes},
  PVENTA198 in 'PVenta\Units\PVENTA198.pas' {frmGondoleros},
  PVENTA199 in 'PVenta\Units\PVENTA199.pas' {frmRepProdOferta},
  PVENTA200 in 'PVenta\Units\PVENTA200.pas' {frmAntiguedadCxC},
  PVENTA201 in 'PVenta\Units\PVENTA201.pas' {frmAntiguedadCxP},
  PVENTA202 in 'PVenta\Units\PVENTA202.pas' {frmConsMovimientoInventario},
  PVENTA203 in 'PVenta\Units\PVENTA203.pas' {frmCuadreCajasIPDefinitivo},
  PVENTA204 in 'PVenta\Units\PVENTA204.pas' {frmRepVentaGerenteProveedor},
  PVENTA205 in 'PVenta\Units\PVENTA205.pas' {frmRepIngresos},
  PVENTA207 in 'PVenta\Units\PVENTA207.pas' {frmCamiones},
  PVENTA208 in 'PVenta\Units\PVENTA208.pas' {frmDetalleMargen},
  PVENTA209 in 'PVenta\Units\PVENTA209.pas' {frmPideClave},
  PVENTA210 in 'PVenta\Units\PVENTA210.pas' {frmResumenVentaProducto},
  PVENTA211 in 'PVenta\Units\PVENTA211.pas' {frmChartResumenVentaProducto},
  PVENTA212 in 'PVenta\Units\PVENTA212.pas' {frmRepVentaProducto},
  PVENTA206 in 'PVenta\Units\PVENTA206.pas' {frmRepInvTransferencia},
  PVENTA213 in 'PVenta\Units\PVENTA213.pas' {frmUnidades},
  PVENTA214 in 'PVenta\Units\PVENTA214.pas' {frmPreciosUnidadMedida},
  PVENTA215 in 'PVenta\Units\PVENTA215.pas' {frmRepCxcGeneral},
  RVENTA129 in 'PVenta\Reports\RVENTA129.pas' {frmRepFacVencCxP},
  PVENTA217 in 'PVenta\Units\PVENTA217.pas' {frmRepProductosDespachados},
  PVENTA218 in 'PVenta\Units\PVENTA218.pas' {frmFormaPagoTicket},
  PVENTA219 in 'PVenta\Units\PVENTA219.pas' {frmTipoProveedor},
  PVENTA220 in 'PVenta\Units\PVENTA220.pas' {frmRepCambioPrecios},
  PVENTA221 in 'PVenta\Units\PVENTA221.pas' {frmMedidores},
  PVENTA222 in 'PVenta\Units\PVENTA222.pas' {frmDatosMedidor},
  PVENTA238 in 'PVenta\Units\PVENTA238.pas' {frmOrdenesFactura},
  PVENTA226 in 'PVenta\Units\PVENTA226.pas' {frmFacturaAutomatica},
  PVENTA227 in 'PVenta\Units\PVENTA227.pas' {frmPreciosUnidadMedidaFacProvee},
  PVENTA228 in 'PVenta\Units\PVENTA228.pas' {frmRepCxCFecha},
  PVENTA229 in 'PVenta\Units\PVENTA229.pas' {frmVerPagos},
  RVENTA62 in 'PVenta\Reports\RVENTA62.pas' {RRepProdVencidos: TQuickRep},
  RVENTA00 in 'PVenta\Reports\RVENTA00.pas' {RPedido: TQuickRep},
  RVENTA01 in 'PVenta\Reports\RVENTA01.pas' {RPedidoSup: TQuickRep},
  RVENTA03 in 'PVenta\Reports\RVENTA03.pas' {RDevolucion: TQuickRep},
  RVENTA04 in 'PVenta\Reports\RVENTA04.pas' {RConsFacturas: TQuickRep},
  RVENTA05 in 'PVenta\Reports\RVENTA05.pas' {RConsBeneficio: TQuickRep},
  RVENTA06 in 'PVenta\Reports\RVENTA06.pas' {RConsProdCliente: TQuickRep},
  RVENTA07 in 'PVenta\Reports\RVENTA07.pas' {RConsFacturasProd: TQuickRep},
  RVENTA08 in 'PVenta\Reports\RVENTA08.pas' {RConsDev: TQuickRep},
  RVENTA09 in 'PVenta\Reports\RVENTA09.pas' {RConsNC: TQuickRep},
  RVENTA10 in 'PVenta\Reports\RVENTA10.pas' {RConsDB: TQuickRep},
  RVENTA11 in 'PVenta\Reports\RVENTA11.pas' {RConsCxC: TQuickRep},
  RVENTA12 in 'PVenta\Reports\RVENTA12.pas' {RConsRecibos: TQuickRep},
  RVENTA13 in 'PVenta\Reports\RVENTA13.pas' {RConsFacProvee: TQuickRep},
  RVENTA14 in 'PVenta\Reports\RVENTA14.pas' {RConsCxP: TQuickRep},
  RVENTA15 in 'PVenta\Reports\RVENTA15.pas' {RMovCentroCostos: TQuickRep},
  RVENTA16 in 'PVenta\Reports\RVENTA16.pas' {RConsDesem: TQuickRep},
  RVENTA17 in 'PVenta\Reports\RVENTA17.pas' {RConsEntrada: TQuickRep},
  RVENTA18 in 'PVenta\Reports\RVENTA18.pas' {RConsConduce: TQuickRep},
  RVENTA19 in 'PVenta\Reports\RVENTA19.pas' {RConsPedidosCli: TQuickRep},
  RVENTA20 in 'PVenta\Reports\RVENTA20.pas' {RConsPedidosProv: TQuickRep},
  RVENTA21 in 'PVenta\Reports\RVENTA21.pas' {RRepClientes: TQuickRep},
  RVENTA22 in 'PVenta\Reports\RVENTA22.pas' {RRepProveedores: TQuickRep},
  RVENTA23 in 'PVenta\Reports\RVENTA23.pas' {RRepMovDia: TQuickRep},
  RVENTA24 in 'PVenta\Reports\RVENTA24.pas' {RFacVencidas: TQuickRep},
  RVENTA25 in 'PVenta\Reports\RVENTA25.pas' {RRepPrecios: TQuickRep},
  RVENTA125 in 'PVenta\Reports\RVENTA125.pas' {RReOrden: TQuickRep},
  RVENTA27 in 'PVenta\Reports\RVENTA27.pas' {RProdFamilia: TQuickRep},
  RVENTA28 in 'PVenta\Reports\RVENTA28.pas' {RRepProdProveedor: TQuickRep},
  RVENTA29 in 'PVenta\Reports\RVENTA29.pas' {RInvFisico: TQuickRep},
  RVENTA30 in 'PVenta\Reports\RVENTA30.pas' {RProdDepto: TQuickRep},
  RVENTA31 in 'PVenta\Reports\RVENTA31.pas' {RCxC: TQuickRep},
  RVENTA32 in 'PVenta\Reports\RVENTA32.pas' {RRecibo: TQuickRep},
  RVENTA33 in 'PVenta\Reports\RVENTA33.pas' {RNotaCredito: TQuickRep},
  RVENTA34 in 'PVenta\Reports\RVENTA34.pas' {RNotaDebito: TQuickRep},
  RVENTA35 in 'PVenta\Reports\RVENTA35.pas' {RDesembolso: TQuickRep},
  RVENTA135 in 'PVenta\Reports\RVENTA135.pas' {RCotizacionFUNDGRUBEL: TQuickRep},
  RVENTA37_SARITA in 'PVenta\Reports\RVENTA37_SARITA.pas' {REntradaAlmSarita: TQuickRep},
  RVENTA127 in 'PVenta\Reports\RVENTA127.pas' {RConduceSarita: TQuickRep},
  RVENTA39 in 'PVenta\Reports\RVENTA39.pas' {RTransferencia: TQuickRep},
  RVENTA40 in 'PVenta\Reports\RVENTA40.pas' {RCxP: TQuickRep},
  RVENTA41 in 'PVenta\Reports\RVENTA41.pas' {REstadoCtaCli: TQuickRep},
  RVENTA42 in 'PVenta\Reports\RVENTA42.pas' {RExistProd: TQuickRep},
  RVENTA43 in 'PVenta\Reports\RVENTA43.pas' {frmAbono},
  RVENTA44 in 'PVenta\Reports\RVENTA44.pas' {RLimites: TQuickRep},
  RVENTA45 in 'PVenta\Reports\RVENTA45.pas' {RepVentaFPago: TQuickRep},
  RVENTA46 in 'PVenta\Reports\RVENTA46.pas' {RepRecFPago: TQuickRep},
  RVENTA47 in 'PVenta\Reports\RVENTA47.pas' {RepDesemFPago: TQuickRep},
  RVENTA48 in 'PVenta\Reports\RVENTA48.pas' {REstadoCtaProv: TQuickRep},
  RVENTA49 in 'PVenta\Reports\RVENTA49.pas' {RAntigSaldoProv: TQuickRep},
  RVENTA51 in 'PVenta\Reports\RVENTA51.pas' {RRepProdVendidos: TQuickRep},
  RVENTA52 in 'PVenta\Reports\RVENTA52.pas' {RRepVentaCliente: TQuickRep},
  RVENTA53 in 'PVenta\Reports\RVENTA53.pas' {RRepEtiqClientes: TQuickRep},
  RVENTA54 in 'PVenta\Reports\RVENTA54.pas' {RConsComision: TQuickRep},
  RVENTA55 in 'PVenta\Reports\RVENTA55.pas' {RConsTransferencia: TQuickRep},
  RVENTA132 in 'PVenta\Reports\RVENTA132.pas' {RCuadreCaceres: TQuickRep},
  RVENTA57 in 'PVenta\Reports\RVENTA57.pas' {RepVentaTipoFac: TQuickRep},
  RVENTA58 in 'PVenta\Reports\RVENTA58.pas' {RepVentaFamilia: TQuickRep},
  RVENTA59 in 'PVenta\Reports\RVENTA59.pas' {RepVentaDepto: TQuickRep},
  RVENTA60 in 'PVenta\Reports\RVENTA60.pas' {RepVentaMarca: TQuickRep},
  RVENTA61 in 'PVenta\Reports\RVENTA61.pas' {RProdMarca: TQuickRep},
  CONT51 in 'CTMContab\Units\CONT51.pas' {frmPasarDocumentos},
  CONT12 in 'CTMContab\Units\CONT12.pas' {frmTiposDoc},
  CONT13 in 'CTMContab\Units\CONT13.pas' {frmNumEntradas},
  CONT14 in 'CTMContab\Units\CONT14.pas' {frmAnexos},
  CONT16 in 'CTMContab\Units\CONT16.pas' {frmConsEntradas},
  CONT17 in 'CTMContab\Units\CONT17.pas' {frmConsMovimiento},
  CONT18 in 'CTMContab\Units\CONT18.pas' {frmRepEntrada},
  CONT19 in 'CTMContab\Units\CONT19.pas' {frmRepDiario},
  CONT20 in 'CTMContab\Units\CONT20.pas' {frmRepResultado},
  CONT21 in 'CTMContab\Units\CONT21.pas' {frmRepBalComprobacion},
  CONT22 in 'CTMContab\Units\CONT22.pas' {frmCierreMes},
  CONT23 in 'CTMContab\Units\CONT23.pas' {frmRepMayorGeneral},
  CONT24 in 'CTMContab\Units\CONT24.pas' {frmRepAnexos},
  CONT25 in 'CTMContab\Units\CONT25.pas' {frmRepSituacion},
  CONT26 in 'CTMContab\Units\CONT26.pas' {frmConsBalances},
  CONT27 in 'CTMContab\Units\CONT27.pas' {frmCheque},
  CONT28 in 'CTMContab\Units\CONT28.pas' {frmConsCheques},
  CONT29 in 'CTMContab\Units\CONT29.pas' {frmConfigCK},
  CONT30 in 'CTMContab\Units\CONT30.pas' {frmAnulaCK},
  CONT31 in 'CTMContab\Units\CONT31.pas' {frmEliminaCK},
  CONT32 in 'CTMContab\Units\CONT32.pas' {frmSolicitud},
  CONT33 in 'CTMContab\Units\CONT33.pas' {frmConsSolicitud},
  CONT34 in 'CTMContab\Units\CONT34.pas' {frmApruebaSol},
  CONT35 in 'CTMContab\Units\CONT35.pas' {frmRepSolicitud},
  CONT36 in 'CTMContab\Units\CONT36.pas' {RepListaSolicitudes: TQuickRep},
  CONT37 in 'CTMContab\Units\CONT37.pas' {frmEliminaSOL},
  CONT38 in 'CTMContab\Units\CONT38.pas' {frmDepositos},
  CONT39 in 'CTMContab\Units\CONT39.pas' {frmConsDepositos},
  CONT40 in 'CTMContab\Units\CONT40.pas' {frmRepCheque},
  CONT41 in 'CTMContab\Units\CONT41.pas' {frmCargosBanco},
  CONT42 in 'CTMContab\Units\CONT42.pas' {frmConsCargosBanco},
  CONT43 in 'CTMContab\Units\CONT43.pas' {frmAnulaDeposito},
  CONT44 in 'CTMContab\Units\CONT44.pas' {frmEliminaDeposito},
  CONT45 in 'CTMContab\Units\CONT45.pas' {frmAnulaCargoBanco},
  CONT46 in 'CTMContab\Units\CONT46.pas' {frmEliminaCargoBanco},
  CONT47 in 'CTMContab\Units\CONT47.pas' {frmLibroBanco},
  CONT48 in 'CTMContab\Units\CONT48.pas' {frmCopiaCatalogo},
  CONT49 in 'CTMContab\Units\CONT49.pas' {RepLibroBanco: TQuickRep},
  CONT50 in 'CTMContab\Units\CONT50.pas' {frmCierreAno},
  RCONT19 in 'CTMContab\Reports\RCONT19.pas' {RepListaCargosBanco: TQuickRep},
  RCONT03 in 'CTMContab\Reports\RCONT03.pas' {RepCatalogo: TQuickRep},
  RCONT04 in 'CTMContab\Reports\RCONT04.pas' {RepConsEntradas: TQuickRep},
  RCONT05 in 'CTMContab\Reports\RCONT05.pas' {RepDocumento: TQuickRep},
  RCONT06 in 'CTMContab\Reports\RCONT06.pas' {RepMovimiento: TQuickRep},
  RCONT07 in 'CTMContab\Reports\RCONT07.pas' {RepEntradaDiario: TQuickRep},
  RCONT08 in 'CTMContab\Reports\RCONT08.pas' {RepDiarioGeneral: TQuickRep},
  RCONT09 in 'CTMContab\Reports\RCONT09.pas' {RepEstResultado: TQuickRep},
  RCONT10 in 'CTMContab\Reports\RCONT10.pas' {RepMayorGeneral: TQuickRep},
  RCONT33 in 'CTMContab\Reports\RCONT33.pas' {RepBalanceCompAnual: TQuickRep},
  RCONT12 in 'CTMContab\Reports\RCONT12.pas' {RepAnexos: TQuickRep},
  RCONT13 in 'CTMContab\Reports\RCONT13.pas' {RepVistaSituacion: TQuickRep},
  RCONT14 in 'CTMContab\Reports\RCONT14.pas' {RepEstadoSituacion: TQuickRep},
  RCONT15 in 'CTMContab\Reports\RCONT15.pas' {RepListaCheques: TQuickRep},
  RCONT34 in 'CTMContab\Reports\RCONT34.pas' {RepCargoBancario: TQuickRep},
  RCONT18 in 'CTMContab\Reports\RCONT18.pas' {RepListaDepositos: TQuickRep},
  CONT15 in 'CTMContab\Units\CONT15.pas' {frmEntradasDiario},
  CONT11 in 'CTMContab\Units\CONT11.pas' {frmCatalogo},
  CONT09 in 'CTMContab\Units\CONT09.pas' {frmBancos},
  RCONT20 in 'CTMContab\Reports\RCONT20.pas' {RepCostoProduccion: TQuickRep},
  CONT52 in 'CTMContab\Units\CONT52.pas' {frmRepCosto},
  RCONT22 in 'CTMContab\Reports\RCONT22.pas' {RepCostoVenta: TQuickRep},
  RCONT23 in 'CTMContab\Reports\RCONT23.pas' {RepBceComparativo: TQuickRep},
  CONT53 in 'CTMContab\Units\CONT53.pas' {frmCFGBceComparativo},
  RCONT24 in 'CTMContab\Reports\RCONT24.pas' {RepBalanceCta: TQuickRep},
  RVENTA63 in 'PVenta\Reports\RVENTA63.pas' {RConteoFisico: TQuickRep},
  RVENTA64 in 'PVenta\Reports\RVENTA64.pas' {RFacturaElegante: TQuickRep},
  RVENTA65 in 'PVenta\Reports\RVENTA65.pas' {RCotizacionElegante: TQuickRep},
  RVENTA66 in 'PVenta\Reports\RVENTA66.pas' {RepMovProductoFactura: TQuickRep},
  RVENTA67 in 'PVenta\Reports\RVENTA67.pas' {RCotMultiple: TQuickRep},
  CONT54 in 'CTMContab\Units\CONT54.pas' {frmCajas},
  CONT55 in 'CTMContab\Units\CONT55.pas' {frmGenerarCheques},
  CONT56 in 'CTMContab\Units\CONT56.pas' {frmRetenciones},
  RVENTA68 in 'PVenta\Reports\RVENTA68.pas' {RLiquidacion: TQuickRep},
  SIGMA02 in 'Units\SIGMA02.pas' {frmadhoc},
  CONT57 in 'CTMContab\Units\CONT57.pas' {frmCategorias},
  CONT58 in 'CTMContab\Units\CONT58.pas' {frmMarcaActivos},
  CONT59 in 'CTMContab\Units\CONT59.pas' {frmFamiliaActivos},
  CONT60 in 'CTMContab\Units\CONT60.pas' {frmActivos},
  CONT61 in 'CTMContab\Units\CONT61.pas' {frmTipoMovActivos},
  CONT62 in 'CTMContab\Units\CONT62.pas' {frmRepActivos},
  CONT63 in 'CTMContab\Units\CONT63.pas' {frmMovActivos},
  RVENTA69 in 'PVenta\Reports\RVENTA69.pas' {RepSolicitados: TQuickRep},
  RVENTA70 in 'PVenta\Reports\RVENTA70.pas' {RepOrdenPedido: TQuickRep},
  RVENTA71 in 'PVenta\Reports\RVENTA71.pas' {RFacturaPreImpresa},
  RVENTA72 in 'PVenta\Reports\RVENTA72.pas' {RDevolucionPreImpresa},
  RH00 in 'RHumanos\Units\RH00.pas' {frmCategoriaEmp},
  RH01 in 'RHumanos\Units\RH01.pas' {frmInstitucion},
  RH02 in 'RHumanos\Units\RH02.pas' {frmTipoSeguros},
  RH03 in 'RHumanos\Units\RH03.pas' {frmCategoriasLic},
  RH04 in 'RHumanos\Units\RH04.pas' {frmTipoEmpleados},
  RH05 in 'RHumanos\Units\RH05.pas' {frmGrupoTrabajo},
  RH06 in 'RHumanos\Units\RH06.pas' {frmGrupoDescuentos},
  RH07 in 'RHumanos\Units\RH07.pas' {frmDiasFeriados},
  RH08 in 'RHumanos\Units\RH08.pas' {frmPosiciones},
  RH09 in 'RHumanos\Units\RH09.pas' {frmNiveles},
  RH10 in 'RHumanos\Units\RH10.pas' {frmPaises},
  RH11 in 'RHumanos\Units\RH11.pas' {frmEstadoCivil},
  RH12 in 'RHumanos\Units\RH12.pas' {frmIdiomas},
  RH13 in 'RHumanos\Units\RH13.pas' {frmMotivos},
  RH14 in 'RHumanos\Units\RH14.pas' {frmNivelSalarial},
  RH15 in 'RHumanos\Units\RH15.pas' {frmTipoEvaluacion},
  RH16 in 'RHumanos\Units\RH16.pas' {frmTipoHora},
  RH17 in 'RHumanos\Units\RH17.pas' {frmTipoIngresos},
  RVENTA77 in 'PVenta\Reports\RVENTA77.pas' {RRepHistorialCli: TQuickRep},
  RVENTA78 in 'PVenta\Reports\RVENTA78.pas' {RRepHistorialSup: TQuickRep},
  RVENTA133 in 'PVenta\Reports\RVENTA133.pas' {RepListaRestBar: TQuickRep},
  RVENTA74 in 'PVenta\Reports\RVENTA74.pas' {RepTicketsCR: TQuickRep},
  RVENTA75 in 'PVenta\Reports\RVENTA75.pas' {RepListaBonos: TQuickRep},
  RVENTA76 in 'PVenta\Reports\RVENTA76.pas' {RFacturaProvee: TQuickRep},
  SERV00 in 'Servicio\Units\SERV00.pas' {frmTecnicos},
  SERV01 in 'Servicio\Units\SERV01.pas' {frmTipoEquipos},
  SERV02 in 'Servicio\Units\SERV02.pas' {frmOrdenServicio},
  SERV06 in 'Servicio\Units\SERV06.pas' {frmDetalleTecnico},
  RSERV00 in 'Servicio\Reports\RSERV00.pas' {ROrdenServicio: TQuickRep},
  SERV04 in 'Servicio\Units\SERV04.pas' {frmSalidaEquipos},
  RH18 in 'RHumanos\Units\RH18.pas' {frmClasificacionNiveles},
  RH19 in 'RHumanos\Units\RH19.pas' {frmHabilidades},
  RH20 in 'RHumanos\Units\RH20.pas' {frmPosicionClasificacion},
  RH21 in 'RHumanos\Units\RH21.pas' {frmPlanesSeguro},
  RH22 in 'RHumanos\Units\RH22.pas' {frmSolicitudEmpleo},
  RH23 in 'RHumanos\Units\RH23.pas' {frmHabilidadEmpleado},
  RVENTA79 in 'PVenta\Reports\RVENTA79.pas' {RFactura2Columnas: TQuickRep},
  PVENTA160 in 'PVenta\Units\PVENTA160.pas' {frmConsProductos},
  SIGMA03 in 'Units\SIGMA03.pas' {frmCambioClave},
  CONT64 in 'CTMContab\Units\CONT64.pas' {frmNCF},
  PVENTA161 in 'PVenta\Units\PVENTA161.pas' {frmverfoto},
  CONT65 in 'CTMContab\Units\CONT65.pas' {frmNCFUnico},
  RCONT25 in 'CTMContab\Reports\RCONT25.pas' {RNCF_Unico: TQuickRep},
  CAJA12 in 'PVenta\Units\CAJA12.pas' {RTicketFormal: TQuickRep},
  CONT66 in 'CTMContab\Units\CONT66.pas' {frmNCFGastosMenores},
  RCONT26 in 'CTMContab\Reports\RCONT26.pas' {RNCF_Gastos_Menores: TQuickRep},
  RVENTA80 in 'PVenta\Reports\RVENTA80.pas' {RRepProductos: TQuickRep},
  RVENTA81 in 'PVenta\Reports\RVENTA81.pas' {RepVentaTipoCliente: TQuickRep},
  RVENTA82 in 'PVenta\Reports\RVENTA82.pas' {RepCumpleanos: TQuickRep},
  RH24 in 'RHumanos\Units\RH24.pas' {frmPosicionesEmpleados},
  RH25 in 'RHumanos\Units\RH25.pas' {frmEstudiosRealizados},
  RH26 in 'RHumanos\Units\RH26.pas' {frmEntrevistas},
  RH27 in 'RHumanos\Units\RH27.pas' {frmRequerimientoPersonal},
  RH28 in 'RHumanos\Units\RH28.pas' {frmElegibles},
  RH29 in 'RHumanos\Units\RH29.pas' {frmElegiblesEmpleados},
  RH30 in 'RHumanos\Units\RH30.pas' {frmEvaluacionSolicitud},
  RH31 in 'RHumanos\Units\RH31.pas' {frmEmpleados},
  RH32 in 'RHumanos\Units\RH32.pas' {frmEmpleadosEstudios},
  RH33 in 'RHumanos\Units\RH33.pas' {frmEmpleadosExperiencia},
  RH34 in 'RHumanos\Units\RH34.pas' {frmEmpleadosDependientes},
  RH35 in 'RHumanos\Units\RH35.pas' {frmEmpleadosPermisos},
  RH36 in 'RHumanos\Units\RH36.pas' {frmEmpleadosLicencias},
  RH37 in 'RHumanos\Units\RH37.pas' {frmEmpleadosAusencias},
  RH38 in 'RHumanos\Units\RH38.pas' {frmEmpleadosHabilidades},
  RH39 in 'RHumanos\Units\RH39.pas' {frmTipoNomina},
  RH40 in 'RHumanos\Units\RH40.pas' {frmEmpleadosMensajes},
  RH41 in 'RHumanos\Units\RH41.pas' {frmVacaciones},
  RH42 in 'RHumanos\Units\RH42.pas' {frmEmpleadosEvaluacion},
  RH43 in 'RHumanos\Units\RH43.pas' {frmPreguntasRespuestas},
  RH44 in 'RHumanos\Units\RH44.pas' {frmInclusionSeguro},
  RH45 in 'RHumanos\Units\RH45.pas' {frmTipoAccionPersonal},
  RH46 in 'RHumanos\Units\RH46.pas' {frmAccionPersonal},
  RH47 in 'RHumanos\Units\RH47.pas' {frmIngresos},
  RH48 in 'RHumanos\Units\RH48.pas' {frmHorasTrabajadas},
  RH49 in 'RHumanos\Units\RH49.pas' {frmDescuentos},
  RH50 in 'RHumanos\Units\RH50.pas' {frmTipoDescuentos},
  RH51 in 'RHumanos\Units\RH51.pas' {frmNomina},
  RH52 in 'RHumanos\Units\RH52.pas' {frmTablaISR},
  RH53 in 'RHumanos\Units\RH53.pas' {frmSemanasSS},
  RH54 in 'RHumanos\Units\RH54.pas' {frmTablaSS},
  RH55 in 'RHumanos\Units\RH55.pas' {frmCalculoPrestaciones},
  RH56 in 'RHumanos\Units\RH56.pas' {frmAFP},
  RH57 in 'RHumanos\Units\RH57.pas' {frmAutorizar},
  RHR00 in 'RHumanos\Reports\RHR00.pas' {RepDGT3: TQuickRep},
  RVENTA83 in 'PVenta\Reports\RVENTA83.pas' {RepRecetas: TQuickRep},
  RVENTA84 in 'PVenta\Reports\RVENTA84.pas' {RepRentabilidad: TQuickRep},
  RVENTA85 in 'PVenta\Reports\RVENTA85.pas' {RCotizacionPreimpresa},
  RHR01 in 'RHumanos\Reports\RHR01.pas' {RVolantePago: TQuickRep},
  RVENTA86 in 'PVenta\Reports\RVENTA86.pas' {frmRepPuntoReorden},
  RVENTA87 in 'PVenta\Reports\RVENTA87.pas' {RRepOfertasOtorgadas: TQuickRep},
  RH58 in 'RHumanos\Units\RH58.pas' {frmSFS},
  RH59 in 'RHumanos\Units\RH59.pas' {frmRepEmpleados},
  RHR03 in 'RHumanos\Reports\RHR03.pas' {RepEmpleados: TQuickRep},
  RHR04 in 'RHumanos\Reports\RHR04.pas' {RepEmpleadoSueldos: TQuickRep},
  RHR05 in 'RHumanos\Reports\RHR05.pas' {RepEmpleadosDirecciones: TQuickRep},
  SIGMA04 in 'Units\SIGMA04.pas' {frmSeleccionConexion},
  CONT67 in 'CTMContab\Units\CONT67.pas' {frmGeneraComprasDGII},
  CONT68 in 'CTMContab\Units\CONT68.pas' {frmConceptos},
  CONT69 in 'CTMContab\Units\CONT69.pas' {frmTipoBienesServicios},
  RH60 in 'RHumanos\Units\RH60.pas' {frmCartaCertificacionIngreso},
  RH61 in 'RHumanos\Units\RH61.pas' {frmAutorizacionCredito},
  RH62 in 'RHumanos\Units\RH62.pas' {frmConsNomina},
  RCONT27 in 'CTMContab\Reports\RCONT27.pas' {RepActivos: TQuickRep},
  RVENTA88 in 'PVenta\Reports\RVENTA88.pas' {RPedidoSup_Preimpreso},
  RVENTA89 in 'PVenta\Reports\RVENTA89.pas' {RepProductosDespachados: TQuickRep},
  RHR06 in 'RHumanos\Reports\RHR06.pas' {RepNominaFormaPago: TQuickRep},
  RVENTA90 in 'PVenta\Reports\RVENTA90.pas' {RepCotizaciones: TQuickRep},
  RVENTA91 in 'PVenta\Reports\RVENTA91.pas' {RepResumenTicket: TQuickRep},
  RCONT28 in 'CTMContab\Reports\RCONT28.pas' {RNCF_Unico_Resumen: TQuickRep},
  RVENTA93 in 'PVenta\Reports\RVENTA93.pas' {RepCuadreCajasIp: TQuickRep},
  RVENTA94 in 'PVenta\Reports\RVENTA94.pas' {RepResumenEjecutivo: TQuickRep},
  RVENTA95 in 'PVenta\Reports\RVENTA95.pas' {RConsBeneficioFamilia: TQuickRep},
  RVENTA96 in 'PVenta\Reports\RVENTA96.pas' {RConsBeneficioTickets: TQuickRep},
  RVENTA97 in 'PVenta\Reports\RVENTA97.pas' {RConsBeneficioProductos: TQuickRep},
  CONT70 in 'CTMContab\Units\CONT70.pas' {frmConfigSituacion},
  SIGMA05 in 'Units\SIGMA05.pas' {frmWeb},
  SIGMA06 in 'Units\SIGMA06.pas' {frmSeleccionFecha},
  CONT71 in 'CTMContab\Units\CONT71.pas' {frmGenera607},
  RVENTA98 in 'PVenta\Reports\RVENTA98.pas' {RProdFamiliaDepto: TQuickRep},
  RVENTA99 in 'PVenta\Reports\RVENTA99.pas' {RepVentaFamiliaDepto: TQuickRep},
  RVENTA100 in 'PVenta\Reports\RVENTA100.pas' {RDevolucionCompra: TQuickRep},
  CONT72 in 'CTMContab\Units\CONT72.pas' {frmRepSituacionAnual},
  RVENTA101 in 'PVenta\Reports\RVENTA101.pas' {RepListaTicketsxHora: TQuickRep},
  RVENTA102 in 'PVenta\Reports\RVENTA102.pas' {RepListaTicketsxCajera: TQuickRep},
  CONT73 in 'CTMContab\Units\CONT73.pas' {frmCuentasAcumulan},
  CONT74 in 'CTMContab\Units\CONT74.pas' {frmRepResultadoAnual},
  RVENTA103 in 'PVenta\Reports\RVENTA103.pas' {RCxCVendedorProvincia: TQuickRep},
  RVENTA104 in 'PVenta\Reports\RVENTA104.pas' {RConsNCProv: TQuickRep},
  RVENTA105 in 'PVenta\Reports\RVENTA105.pas' {RCxCGeneral: TQuickRep},
  RVENTA106 in 'PVenta\Reports\RVENTA106.pas' {RepProdOferta: TQuickRep},
  CONT75 in 'CTMContab\Units\CONT75.pas' {frmConsComprobantes},
  RCONT29 in 'CTMContab\Reports\RCONT29.pas' {RComprobantes: TQuickRep},
  CONT76 in 'CTMContab\Units\CONT76.pas' {frmSeleccionNCF},
  RCONT30 in 'CTMContab\Reports\RCONT30.pas' {RComprobantesDetalle: TQuickRep},
  RH63 in 'RHumanos\Units\RH63.pas' {frmConsNovedadesNomina},
  CONT77 in 'CTMContab\Units\CONT77.pas' {frmInformacionNCF},
  RVENTA107 in 'PVenta\Reports\RVENTA107.pas' {RMovimientoInventario: TQuickRep},
  RVENTA108 in 'PVenta\Reports\RVENTA108.pas' {RRepHistorialCliTipo: TQuickRep},
  RVENTA109 in 'PVenta\Reports\RVENTA109.pas' {RepCuadreCajasIpDefinitivo: TQuickRep},
  RVENTA110 in 'PVenta\Reports\RVENTA110.pas' {RepIngresos: TQuickRep},
  CONT78 in 'CTMContab\Units\CONT78.pas' {frmNotificacionComprobantes},
  CONT79 in 'CTMContab\Units\CONT79.pas' {frmNumerosRNC},
  CONT80 in 'CTMContab\Units\CONT80.pas' {frmActNumeroRNC},
  RVENTA111 in 'PVenta\Reports\RVENTA111.pas' {RInvTransferencia: TQuickRep},
  RVENTA112 in 'PVenta\Reports\RVENTA112.pas' {RepVentaGerenteProveedor: TQuickRep},
  CONT81 in 'CTMContab\Units\CONT81.pas' {frmGenera608},
  RVENTA113 in 'PVenta\Reports\RVENTA113.pas' {RBeneficioBruto: TQuickRep},
  RVENTA114 in 'PVenta\Reports\RVENTA114.pas' {RepVentaProducto: TQuickRep},
  RVENTA115 in 'PVenta\Reports\RVENTA115.pas' {RFacturaGrabadoExento: TQuickRep},
  RH64 in 'RHumanos\Units\RH64.pas' {frmConsNovedades},
  RHR07 in 'RHumanos\Reports\RHR07.pas' {RConsNovedades: TQuickRep},
  RVENTA116 in 'PVenta\Reports\RVENTA116.pas' {RCxPGeneral: TQuickRep},
  RVENTA117 in 'PVenta\Reports\RVENTA117.pas' {RRepProdDespachados: TQuickRep},
  RVENTA118 in 'PVenta\Reports\RVENTA118.pas' {RTicketsAgregados: TQuickRep},
  RVENTA119 in 'PVenta\Reports\RVENTA119.pas' {RProductosDespachados: TQuickRep},
  RVENTA120 in 'PVenta\Reports\RVENTA120.pas' {RCambioPrecios: TQuickRep},
  CONT82 in 'CTMContab\Units\CONT82.pas' {frmConsGastosMenores},
  CONT83 in 'CTMContab\Units\CONT83.pas' {frmCashflowGrupos},
  CONT84 in 'CTMContab\Units\CONT84.pas' {frmCashflowSubgrupos},
  CONT85 in 'CTMContab\Units\CONT85.pas' {frmCashflowConceptos},
  CONT86 in 'CTMContab\Units\CONT86.pas' {frmCashflow},
  CONT87 in 'CTMContab\Units\CONT87.pas' {frmCashflowTransaccion},
  CONT88 in 'CTMContab\Units\CONT88.pas' {frmCashflowActTransaccion},
  PVENTA224 in 'PVenta\Units\PVENTA224.pas' {frmBuscaTemporal},
  RHR08 in 'RHumanos\Reports\RHR08.pas' {RepNominaDescuento: TQuickRep},
  CONT89 in 'CTMContab\Units\CONT89.pas' {frmCashFlow_ImprimeMes},
  RCONT31 in 'CTMContab\Reports\RCONT31.pas' {RCashflow_Mes: TQuickRep},
  RVENTA121 in 'PVenta\Reports\RVENTA121.pas' {RConsTicketsProd: TQuickRep},
  RVENTA122 in 'PVenta\Reports\RVENTA122.pas' {RFacturaClinico: TQuickRep},
  CONT90 in 'CTMContab\Units\CONT90.pas' {frmCashflow_Mensajes},
  SIGMA07 in 'Units\SIGMA07.pas' {frmAdministracion},
  SIGMA08 in 'Units\SIGMA08.pas' {frmCentrosXCuenta},
  CONT91 in 'CTMContab\Units\CONT91.pas' {frmTransferenciaBanco},
  RHR09 in 'RHumanos\Reports\RHR09.pas' {RConsNovedadesDetalle: TQuickRep},
  PVENTAANULAPEDIDO in 'PVenta\Units\PVENTAANULAPEDIDO.pas' {frmAnulaPedido},
  PVENTAPRODUCTOSXALMACEN in 'PVenta\Units\PVENTAPRODUCTOSXALMACEN.pas' {frmProductosXAlmacen},
  uEnvios in 'Project\uEnvios.pas' {frmEnvio},
  magsubs1 in 'UsbKey\magsubs1.pas',
  magwmi in 'UsbKey\magwmi.pas',
  WbemScripting_TLB in 'UsbKey\WbemScripting_TLB.pas',
  smartapi in 'UsbKey\smartapi.pas',
  RVENTA123 in 'PVenta\Reports\RVENTA123.pas' {RAnalisisCompra_Venta: TQuickRep},
  SERV05 in 'Servicio\Units\SERV05.pas' {frmConsServicios},
  SERV08 in 'Servicio\Units\SERV08.pas' {frmAccesoTec2},
  SERV03 in 'Servicio\Units\SERV03.pas' {frmDetalleOrdenServicio},
  SERV09 in 'Servicio\Units\SERV09.pas' {frmMemo},
  RSERV01 in 'Servicio\Reports\RSERV01.pas' {RConsServicios: TQuickRep},
  RVENTA124 in 'PVenta\Reports\RVENTA124.pas' {REstadoCtaCliConsolidado: TQuickRep},
  RCONT32 in 'CTMContab\Reports\RCONT32.pas' {RNCF_Gastos_Menores_lista: TQuickRep},
  PVENTA44 in 'PVenta\Units\PVENTA44.pas' {frmConsFacturas},
  PVENTA231 in 'PVenta\Units\PVENTA231.pas' {frmEnvioMant},
  RENVIO01 in 'PVenta\Units\RENVIO01.pas' {RENVIO: TQuickRep},
  RLISTADOENVIO01 in 'PVenta\Units\RLISTADOENVIO01.pas' {RListadoEnvio: TQuickRep},
  PENVIO02 in 'PVenta\Units\PENVIO02.pas' {frmEnvioM2},
  PTIKET001 in 'PVenta\Units\PTIKET001.pas' {frmBoleteria},
  Barcode in 'Units\Barcode.pas',
  bcchksum in 'Units\bcchksum.pas',
  Barcode2 in 'Units\Barcode2.pas',
  RH65 in 'RHumanos\Units\RH65.pas' {frmNominaBanco},
  PTIKET002 in 'PVenta\Units\PTIKET002.pas' {frmBoletoPrecio},
  PTIKET003 in 'PVenta\Units\PTIKET003.pas' {frmConsBoletos},
  PTIKET004 in 'PVenta\Units\PTIKET004.pas' {RListadoBoletos: TQuickRep},
  PTIKET005 in 'PVenta\Units\PTIKET005.pas' {frmBoletoPago},
  PRENTA001 in 'PVenta\Units\PRENTA001.pas' {frmRentaOld},
  PVENTA18 in 'PVenta\Units\PVENTA18.pas' {frmFactura},
  PVENTA26 in 'PVenta\Units\PVENTA26.pas' {frmCotizacion},
  UFrm_Consulta in 'UFrm_Consulta.pas' {Frm_Consulta},
  PVENTAREPVENC in 'PVenta\Units\PVENTAREPVENC.pas' {frmRepVencimiento},
  PVENTAASEG in 'PVenta\Units\PVENTAASEG.pas' {frmAseguradoras},
  RCONT17 in 'CTMContab\Reports\RCONT17.pas' {RepCheque: TQuickRep},
  USerial in 'PVenta\Units\USerial.pas' {FSerial},
  RVENTA26_SARITA in 'PVenta\Reports\RVENTA26_SARITA.pas' {RValorInvSarita: TQuickRep},
  PVenta233 in 'PVenta\Units\PVenta233.pas' {frmListadoProdFalt},
  RVENTA128 in 'PVenta\Reports\RVENTA128.pas' {RFacturaSteelTec: TQuickRep},
  RVENTA131 in 'PVenta\Reports\RVENTA131.pas' {RCotizacionCaceresEquipos: TQuickRep},
  PVENTA216 in 'PVenta\Units\PVENTA216.pas' {frmRepCxPGeneral},
  RVENTA50 in 'PVenta\Reports\RVENTA50.pas' {RFacVencidasProv: TQuickRep},
  PVenta234 in 'PVenta\Units\PVenta234.pas' {FrmFecha},
  PVenta235 in 'PVenta\Units\PVenta235.pas' {FrmSelFecha},
  RVENTA126 in 'PVenta\Reports\RVENTA126.pas' {RFacturaSarita: TQuickRep},
  PVENTA237 in 'PVenta\Units\PVENTA237.pas' {frmConsTicketTransp},
  PVenta236 in 'PVenta\Units\PVenta236.pas' {FrmLiquidacionTickets},
  PVENTA223 in 'PVenta\Units\PVENTA223.pas' {frmPedidosFactura},
  PVENTA37 in 'PVenta\Units\PVENTA37.pas' {frmPideCajero},
  PVenta240 in 'PVenta\Units\PVenta240.pas' {FrmProdConduce},
  PVenta241 in 'PVenta\Units\PVenta241.pas' {frmConsFacturasRestBar},
  PVENTA242 in 'PVenta\Units\PVENTA242.pas' {FrmCotizacionVencidas},
  PVENTA243 in 'PVenta\Units\PVENTA243.pas' {FrmComentCoti},
  PVENTA244 in 'PVenta\Units\PVENTA244.pas' {FrmConfCorreo},
  RCONT11 in 'CTMContab\Reports\RCONT11.pas' {RepBalanceComp: TQuickRep},
  RVENTA134 in 'PVenta\Reports\RVENTA134.pas' {RFacturaFUNDGRUBEL: TQuickRep},
  SIGMA09 in 'Units\SIGMA09.pas' {FrmActScripts},
  SIGMA10 in 'Units\SIGMA10.pas' {DM_Update: TDataModule},
  RCONT16 in 'CTMContab\Reports\RCONT16.pas' {RepSolicitud: TQuickRep},
  CONT92 in 'CTMContab\Units\CONT92.pas' {Frm_Balance_Bancos},
  CONT93 in 'CTMContab\Units\CONT93.pas' {frmDispBanco},
  RVENTA130 in 'PVenta\Reports\RVENTA130.pas' {RFacturaCaceresEquipos: TQuickRep},
  EASendMailObjLib_TLB in '..\..\..\..\..\Program Files (x86)\Borland\Delphi7\Imports\EASendMailObjLib_TLB.pas',
  PVENTA245 in 'PVenta\Units\PVENTA245.pas' {frmCierreDiaCardnet},
  PVENTA246 in 'PVenta\Units\PVENTA246.pas' {FrmRecibosPagoDestino},
  RVENTA56 in 'PVenta\Reports\RVENTA56.pas' {RCuadre: TQuickRep},
  PVENTA247 in 'PVenta\Units\PVENTA247.pas' {frmLocalidades},
  RVENTA38 in 'PVenta\Reports\RVENTA38.pas' {RConduce: TQuickRep},
  RVENTA37 in 'PVenta\Reports\RVENTA37.pas' {REntradaAlm: TQuickRep},
  RVENTA26 in 'PVenta\Reports\RVENTA26.pas' {RValorInv: TQuickRep},
  RVENTA73 in 'PVenta\Reports\RVENTA73.pas' {RepListaTickets: TQuickRep},
  RVENTA02 in 'PVenta\Reports\RVENTA02.pas' {RFactura: TQuickRep},
  RVENTA36 in 'PVenta\Reports\RVENTA36.pas' {RCotizacion: TQuickRep},
  prueba in 'PVenta\Units\prueba.pas' {frmprueba},
  PVENTA249 in 'PVenta\Units\PVENTA249.pas' {frmDigitarClave},
  PVENTA250 in 'PVenta\Units\PVENTA250.pas' {FormAnularBoleto},
  DelphiZXingQRCode in 'PVenta\Reports\DelphiZXingQRCode.pas',
  FacturacionElectronicaDGII_TLB in '..\..\..\..\..\Program Files (x86)\Borland\Delphi7\Imports\FacturacionElectronicaDGII_TLB.pas',
  PVENTA251 in 'PVenta\Units\PVENTA251.pas',
  PVENTA252 in 'PVenta\Units\PVENTA252.pas' {frmeNCF},
  PROGRESO in 'PVenta\Units\PROGRESO.pas' {frmProgress},
  POS24 in 'PVenta\Reports\POS24.pas' {RFacturaP: TQuickRep},
  RVENTA136 in 'PVenta\Reports\RVENTA136.pas' {RFacturaCorta: TQuickRep},
  RVENTA137 in 'PVenta\Reports\RVENTA137.pas' {RFacturaConstruccion: TQuickRep},
  PVENTA253 in 'PVenta\Units\PVENTA253.pas' {frmSelVendPorc},
  uFrmPopupDGII in 'PVenta\Units\uFrmPopupDGII.pas' {FrmPopupDGII};

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'DASHA';
  Application.HelpFile := 'd:\D&RTecnologic\Fuentes\Dasha-Administrativo\Project\Sigma.hlp';
  Application.CreateForm(TDM, DM);
  Application.CreateForm(TfrmMain, frmMain);
  Application.CreateForm(TDM_Update, DM_Update);
  Application.Run;


    end.
